"""PR Generator: Creates automated PRs for common fix patterns."""

import json
import subprocess
import tempfile
from pathlib import Path


def create_branch(issue_number: int, base_branch: str = "main") -> str:
    """Create a feature branch for the fix."""
    branch = f"fix/auto-{issue_number}-{int(__import__('time').time())}"
    subprocess.run(["git", "checkout", base_branch], check=True)
    subprocess.run(["git", "checkout", "-b", branch], check=True)
    return branch


def commit_and_push(branch: str, message: str):
    """Stage, commit, and push changes."""
    subprocess.run(["git", "add", "-A"], check=True)
    subprocess.run(["git", "commit", "-m", message], check=True)
    subprocess.run(["git", "push", "origin", branch], check=True)


def create_pull_request(
    title: str, body: str, branch: str, base: str = "main"
) -> dict:
    """Create a PR via gh CLI."""
    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", base,
            "--head", branch,
        ],
        capture_output=True, text=True, check=True,
    )
    return {"url": result.stdout.strip(), "branch": branch}


def generate_fix_patch(issue_body: str) -> str:
    """Placeholder: uses Sentinel agent to generate a fix patch.
    Replace with actual sentinel-core integration."""
    return "# Fix generated by Sentinel Caretaker\n"


def handle_issue(issue: dict) -> dict:
    """Main entry: generate fix PR for a triaged issue."""
    issue_number = issue["number"]
    title = issue.get("title", "Automated fix")
    body = issue.get("body", "")

    patch = generate_fix_patch(body)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo_path = Path(tmpdir) / "repo"
        subprocess.run(["git", "clone", os.environ["REPO_URL"], str(repo_path)], check=True)
        os.chdir(repo_path)

        branch = create_branch(issue_number)
        Path("fix.patch").write_text(patch)
        pr_body = f"## Automated Fix\n\nCloses #{issue_number}\n\nGenerated by Sentinel Caretaker."
        result = create_pull_request(title, pr_body, branch)
        return result


if __name__ == "__main__":
    import os, sys
    event = json.loads(sys.stdin.read()) if not sys.stdin.isatty() else {}
    print(json.dumps(handle_issue(event), indent=2))
