use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::sync::Mutex;

const MEMORY_FILE: &str = "PROJECT.md";

/// Reads and writes agent session memory to a project-level file.
pub struct MemoryFileManager {
    path: PathBuf,
    session_summaries: Arc<Mutex<Vec<String>>>,
}

impl MemoryFileManager {
    pub fn new(project_root: &Path) -> Self {
        Self {
            path: project_root.join(MEMORY_FILE),
            session_summaries: Arc::new(Mutex::new(Vec::new())),
        }
    }

    /// Add a summary of the current session (called after pipeline completes).
    pub async fn record_session(&self, summary: String) {
        let mut summaries = self.session_summaries.lock().await;
        summaries.push(summary);
    }

    /// Read the current memory file content.
    pub async fn read_memory(&self) -> Result<String, String> {
        if self.path.exists() {
            tokio::fs::read_to_string(&self.path)
                .await
                .map_err(|e| e.to_string())
        } else {
            Ok(String::new())
        }
    }

    /// Flush all accumulated session summaries to the memory file.
    pub async fn flush(&self) -> Result<(), String> {
        let summaries = self.session_summaries.lock().await;
        if summaries.is_empty() {
            return Ok(());
        }

        // Read existing content
        let existing = if self.path.exists() {
            tokio::fs::read_to_string(&self.path)
                .await
                .map_err(|e| e.to_string())?
        } else {
            String::new()
        };

        let mut output = String::new();
        output.push_str("# Project Memory\n\n");

        // Existing memory section (extract after "## Session History" if present)
        if let Some(idx) = existing.find("## Session History") {
            output.push_str(&existing[..idx]);
        } else {
            output.push_str(&existing);
            if !existing.is_empty() && !existing.ends_with('\n') {
                output.push('\n');
            }
        }

        output.push_str("\n## Session History\n\n");

        for (i, summary) in summaries.iter().enumerate() {
            output.push_str(&format!("### Session {}\n{}\n\n", i + 1, summary));
        }

        output.push_str("---\n*Auto-generated by Sentinel memory manager*\n");

        // Ensure directory exists
        if let Some(parent) = self.path.parent() {
            tokio::fs::create_dir_all(parent)
                .await
                .map_err(|e| e.to_string())?;
        }

        tokio::fs::write(&self.path, &output)
            .await
            .map_err(|e| e.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_memory_file_create() {
        let dir = std::env::temp_dir().join(format!("mem-test-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        let mfm = MemoryFileManager::new(&dir);
        mfm.record_session("Fixed bug in parser".to_string()).await;
        mfm.flush().await.unwrap();
        let content = std::fs::read_to_string(dir.join(MEMORY_FILE)).unwrap();
        assert!(content.contains("Fixed bug in parser"));
        assert!(content.contains("Session History"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
